# Generated by Django 5.2.8 on 2025-11-29 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blindbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blindbox',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blindbox',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blindbox.category'),
        ),
        migrations.AddField(
            model_name='openrecord',
            name='blindbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blindbox.blindbox'),
        ),
        migrations.AddField(
            model_name='openrecord',
            name='matched_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_boxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_boxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='openrecord',
            unique_together={('user', 'blindbox')},
        ),
    ]
