# Generated by Django 5.2.8 on 2025-12-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
