# Generated by Django 5.2.8 on 2025-12-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_is_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='is_viewed',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
