# Generated by Django 5.2.8 on 2025-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blindbox',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
