# Generated by Django 5.2.8 on 2025-12-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blindbox', '0002_blindbox_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blindbox',
            name='is_active',
        ),
    ]
